name: CI

on:
  push:
    branches:
    - master

jobs:
  split-upm:
    name: update upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: update upm branch
      run: |
        echo '### head info'
        git log -1

        echo '### split upm branch'
        git subtree split -P "$PKG_ROOT" -b upm

        echo '### update remote upm branch'
        git push origin upm
      env:
        PKG_ROOT: Assets/NaughtyAttributes
